media:
  input: images
  output: images

content:
  - name: "Website Editor"
    type: object
    path: content.json
    preview: 
      url: https://anubisdigital.github.io/Hacker/
    fields:
      - name: brand_color
        label: "Brand Color"
        type: string
      - name: bg_color
        label: "Background Color"
        type: string
      - name: index_title
        label: "Home Page Heading"
        type: string
      - name: index_image
        label: "Home Page Image"
        type: image
      - name: other_title
        label: "Other Page Heading"
        type: string
      - name: other_image
        label: "Other Page Image"
        type: image
